name: npm-build
on:
  push:
    branches: main
env:
  USER: 'pm-random'
  REPO: 'pm-random.github.io'
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v2
    - name: Clean install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Push to gh-pages
      run: |
        cd dist
        git init --initial-branch gh-pages
        git config user.name 'npm-builder [bot]'
        git config user.email 'npm-builder@github.com'
        git add -A
        git commit -m 'build'
        git push -f "https://$USER:${{ secrets.GITHUB_TOKEN }}@github.com/$USER/$REPO.git"
